package hcl

// Import is the inverse of Generate: it parses Terraform configuration text
// back into a graph.Model. It lives in the domain because HCL parsing is pure
// token work with no I/O, and it deliberately does NOT shell out to terraform
// — it reads the source statically with hclsyntax. That trades some accuracy
// (it cannot resolve computed values, modules, or count/for_each) for zero
// infrastructure, which is the right first step for read-only visualization.
//
// The one non-obvious move is reference resolution. HCL writes a dependency by
// address (aws_vpc.main.id), but the model references by ResourceID (a UUID),
// so identity survives a rename. Import therefore runs in two passes: pass one
// registers every resource and records an address -> ID index; pass two
// resolves each attribute's traversals against that index. This is exactly
// renderValue in generator.go run backwards.
//
// Anything Import cannot faithfully represent — nested blocks, references to
// var/local/data/module, function calls, interpolations, count/for_each — is
// reported as a Diagnostic and skipped, never guessed. A non-nil error means
// the HCL did not parse at all; valid-but-unsupported input yields diagnostics.

import (
	"fmt"
	"sort"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/zclconf/go-cty/cty"

	"github.com/JoshF8/calco/apps/server/internal/domain/graph"
)

// Diagnostic records one construct the importer could not represent. It is
// informational, not fatal: Import skips the construct and continues, so the
// caller can honestly tell the user what was dropped rather than silently
// losing it or inventing a value.
type Diagnostic struct {
	File      string `json:"file,omitempty"`
	Address   string `json:"address,omitempty"`   // "type.name" when known
	Attribute string `json:"attribute,omitempty"` // argument name when applicable
	Reason    string `json:"reason"`
}

// nonResourceRoots are traversal roots that are never a resource reference, so
// a clearer diagnostic can be given than a bare "not found".
var nonResourceRoots = map[string]bool{
	"var": true, "local": true, "data": true, "module": true,
	"each": true, "count": true, "self": true, "path": true, "terraform": true,
}

// structuralBlocks carry no graph data and are regenerated by Generate, so the
// importer ignores them silently (no diagnostic noise on a round-trip).
var structuralBlocks = map[string]bool{"terraform": true, "provider": true}

// Import parses Terraform files (filename -> HCL source) into a graph.Model,
// plus the diagnostics for everything it could not represent. The returned
// model is not validated here; callers run Model.Validate as needed.
func Import(files map[string]string) (*graph.Model, []Diagnostic, error) {
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names) // deterministic order across files

	type parsedResource struct {
		id    graph.ResourceID
		block *hclsyntax.Block
		file  string
	}

	model := graph.NewModel()
	index := map[string]graph.ResourceID{} // "type.name" -> ID
	var diags []Diagnostic
	var resources []parsedResource

	// Pass 1: register every resource so references can resolve across files.
	for _, name := range names {
		f, pd := hclsyntax.ParseConfig([]byte(files[name]), name, hcl.Pos{Line: 1, Column: 1})
		if pd.HasErrors() {
			return nil, nil, fmt.Errorf("hcl: %s does not parse: %s", name, pd.Error())
		}
		body, ok := f.Body.(*hclsyntax.Body)
		if !ok {
			return nil, nil, fmt.Errorf("hcl: %s has an unexpected body type", name)
		}
		for _, b := range body.Blocks {
			if b.Type != "resource" {
				if !structuralBlocks[b.Type] {
					diags = append(diags, Diagnostic{File: name, Reason: fmt.Sprintf("%q block not imported yet", b.Type)})
				}
				continue
			}
			if len(b.Labels) != 2 {
				diags = append(diags, Diagnostic{File: name, Reason: "resource block needs exactly a type and a name label"})
				continue
			}
			typ, nm := b.Labels[0], b.Labels[1]
			addr := typ + "." + nm
			if _, dup := index[addr]; dup {
				diags = append(diags, Diagnostic{File: name, Address: addr, Reason: "duplicate resource address; keeping the first"})
				continue
			}
			id := graph.NewResourceID()
			if err := model.AddResource(graph.Resource{ID: id, Type: typ, Name: nm}); err != nil {
				diags = append(diags, Diagnostic{File: name, Address: addr, Reason: err.Error()})
				continue
			}
			index[addr] = id
			resources = append(resources, parsedResource{id: id, block: b, file: name})
		}
	}

	// Pass 2: resolve each resource's attributes against the address index.
	for _, pr := range resources {
		addr := addressOf(model, pr.id)
		src := []byte(files[pr.file])

		// Nested blocks (ingress {}, vpc_config {}, …) aren't modeled yet.
		for _, nb := range pr.block.Body.Blocks {
			diags = append(diags, Diagnostic{File: pr.file, Address: addr, Attribute: nb.Type, Reason: "nested block not modeled yet"})
		}

		attrNames := make([]string, 0, len(pr.block.Body.Attributes))
		for n := range pr.block.Body.Attributes {
			attrNames = append(attrNames, n)
		}
		sort.Strings(attrNames) // deterministic
		for _, an := range attrNames {
			val, d := convertExpr(pr.block.Body.Attributes[an].Expr, src, index)
			if d != nil {
				d.File, d.Address, d.Attribute = pr.file, addr, an
				diags = append(diags, *d)
				continue
			}
			if err := model.SetAttribute(pr.id, an, val); err != nil {
				diags = append(diags, Diagnostic{File: pr.file, Address: addr, Attribute: an, Reason: err.Error()})
			}
		}
	}

	// Edges mirror the refs so the canvas can draw connections without
	// re-deriving them; the generator ignores them and uses the refs directly.
	model.Edges = model.DeriveEdges()
	return model, diags, nil
}

func addressOf(m *graph.Model, id graph.ResourceID) string {
	if r, ok := m.FindResource(id); ok {
		return r.Address()
	}
	return ""
}

// convertExpr turns one HCL expression into an AttrValue, or returns a
// Diagnostic (with only Reason set; the caller fills in file/address/attr) when
// the expression is not a literal, a resource reference, or a list of those.
func convertExpr(expr hclsyntax.Expression, src []byte, index map[string]graph.ResourceID) (graph.AttrValue, *Diagnostic) {
	switch e := expr.(type) {
	case *hclsyntax.ScopeTraversalExpr:
		return convertTraversal(e.Traversal, index)
	case *hclsyntax.TemplateWrapExpr:
		// A template that is exactly one interpolation, e.g.
		// "${aws_vpc.main.id}" — the Terraform 0.11-era reference style. Unwrap
		// and convert the inner expression (usually a traversal).
		return convertExpr(e.Wrapped, src, index)
	case *hclsyntax.TemplateExpr:
		// A quoted string. A single-part template is either a plain literal
		// ("t2.micro") or a lone interpolation ("${aws_vpc.main.id}"); convert
		// the sole part so the old quoted-reference style still resolves. A
		// multi-part template concatenates literal text and interpolations
		// (e.g. "prefix-${x}"), which the flat model cannot represent.
		if len(e.Parts) == 1 {
			return convertExpr(e.Parts[0], src, index)
		}
		return graph.AttrValue{}, &Diagnostic{Reason: "interpolated string with multiple parts is not representable"}
	case *hclsyntax.TupleConsExpr:
		items := make([]graph.AttrValue, 0, len(e.Exprs))
		for _, sub := range e.Exprs {
			v, d := convertExpr(sub, src, index)
			if d != nil {
				return graph.AttrValue{}, &Diagnostic{Reason: "list element not representable: " + d.Reason}
			}
			items = append(items, v)
		}
		return graph.List(items...), nil
	default:
		// Everything else must be a constant to be representable: evaluating
		// with a nil context succeeds for pure literals and fails for anything
		// referencing a symbol (interpolations, functions, var/local/…).
		val, vd := expr.Value(nil)
		if vd.HasErrors() {
			return graph.AttrValue{}, &Diagnostic{Reason: "not a literal or resource reference (interpolation, function, or variable)"}
		}
		return convertScalar(val, expr, src)
	}
}

// convertTraversal resolves a resource-attribute traversal (type.name.attr)
// against the address index. Non-resource roots and unknown addresses are
// diagnosed and skipped rather than emitted as dangling references.
func convertTraversal(trav hcl.Traversal, index map[string]graph.ResourceID) (graph.AttrValue, *Diagnostic) {
	if len(trav) < 3 {
		return graph.AttrValue{}, &Diagnostic{Reason: "reference is not a resource attribute (type.name.attribute)"}
	}
	root, ok0 := trav[0].(hcl.TraverseRoot)
	a1, ok1 := trav[1].(hcl.TraverseAttr)
	a2, ok2 := trav[2].(hcl.TraverseAttr)
	if !ok0 || !ok1 || !ok2 {
		return graph.AttrValue{}, &Diagnostic{Reason: "reference has an index or unexpected shape"}
	}
	if nonResourceRoots[root.Name] {
		return graph.AttrValue{}, &Diagnostic{Reason: fmt.Sprintf("reference to %s.* is not a resource (not modeled yet)", root.Name)}
	}
	addr := root.Name + "." + a1.Name
	id, ok := index[addr]
	if !ok {
		return graph.AttrValue{}, &Diagnostic{Reason: fmt.Sprintf("reference to %s not found among the imported resources", addr)}
	}
	return graph.Ref(id, a2.Name), nil
}

// convertScalar turns a constant cty value into a literal AttrValue. Numbers
// keep their exact source text (via the expression's range) so precision and
// int-vs-float identity survive, mirroring how the generator stores them.
func convertScalar(val cty.Value, expr hclsyntax.Expression, src []byte) (graph.AttrValue, *Diagnostic) {
	if val.IsNull() {
		return graph.AttrValue{}, &Diagnostic{Reason: "null values are not modeled"}
	}
	switch val.Type() {
	case cty.String:
		return graph.String(val.AsString()), nil
	case cty.Bool:
		return graph.Bool(val.True()), nil
	case cty.Number:
		rng := expr.Range()
		if rng.Start.Byte >= 0 && rng.End.Byte <= len(src) && rng.Start.Byte < rng.End.Byte {
			if v := graph.NumberText(string(src[rng.Start.Byte:rng.End.Byte])); v.Valid() {
				return v, nil
			}
		}
		// Fall back to cty's canonical form if the source text isn't a clean
		// literal (e.g. a parenthesised or negated expression).
		return graph.NumberText(val.AsBigFloat().Text('f', -1)), nil
	default:
		return graph.AttrValue{}, &Diagnostic{Reason: "unsupported value type " + val.Type().FriendlyName()}
	}
}
