package hcl

// Import is the inverse of Generate: it parses Terraform configuration text
// back into a graph.Model. It lives in the domain because HCL parsing is pure
// token work with no I/O, and it deliberately does NOT shell out to terraform
// — it reads the source statically with hclsyntax. That trades some accuracy
// (it cannot resolve computed values, remote modules, or count/for_each) for
// zero infrastructure, which is the right first step for read-only
// visualization. Modules whose source is a local directory inside the import
// are resolved statically: they become graph.Module groupings with the source
// resources nested behind the invocation.
//
// The one non-obvious move is reference resolution. HCL writes a dependency by
// address (aws_vpc.main.id), but the model references by ResourceID (a UUID),
// so identity survives a rename. Import therefore runs in two passes: pass one
// registers every resource and records an address -> ID index; pass two
// resolves each attribute's traversals against that index. This is exactly
// renderValue in generator.go run backwards.
//
// Resources' nested blocks (ingress, egress, default_action, ebs_block_device,
// …) are converted recursively into graph.Block values in source order;
// label-bearing blocks (dynamic, provisioner) are not yet modeled and are
// diagnosed rather than guessed.
//
// Anything Import cannot faithfully represent — label-bearing or
// structural blocks, references to var/local/data/module, function calls,
// interpolations, count/for_each, and module invocations with remote or unknown
// sources — is reported as a Diagnostic and skipped, never guessed. A non-nil
// error means the HCL did not parse at all; valid-but-unsupported input yields
// diagnostics.

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/zclconf/go-cty/cty"

	"github.com/JoshF8/calco/apps/server/internal/domain/graph"
)

// Diagnostic records one construct the importer could not represent. It is
// informational, not fatal: Import skips the construct and continues, so the
// caller can honestly tell the user what was dropped rather than silently
// losing it or inventing a value.
type Diagnostic struct {
	File      string `json:"file,omitempty"`
	Address   string `json:"address,omitempty"`   // "type.name" when known
	Attribute string `json:"attribute,omitempty"` // argument name when applicable
	Reason    string `json:"reason"`
}

// nonResourceRoots are traversal roots that are never a resource reference, so
// a clearer diagnostic can be given than a bare "not found".
var nonResourceRoots = map[string]bool{
	"var": true, "local": true, "data": true, "module": true,
	"each": true, "count": true, "self": true, "path": true, "terraform": true,
}

// structuralBlocks carry no graph data and are regenerated by Generate, so the
// importer ignores them silently (no diagnostic noise on a round-trip).
var structuralBlocks = map[string]bool{"terraform": true, "provider": true}

// Import parses Terraform files (filename -> HCL source) into a graph.Model,
// plus the diagnostics for everything it could not represent. The returned
// model is not validated here; callers run Model.Validate as needed.
//
// Local modules — a `module` block whose source is a directory inside the
// imported file set — are resolved: the invocation becomes a graph.Module that
// groups the resources defined under that directory (one container per source
// dir, even if several invocations share it), and its variable/output blocks
// are treated as the module's interface (silent, not diagnosed). Modules with
// remote or unknown sources stay diagnosed until a fetcher lands.
func Import(files map[string]string) (*graph.Model, []Diagnostic, error) {
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names) // deterministic order across files

	type parsedResource struct {
		id    graph.ResourceID
		block *hclsyntax.Block
		file  string
	}

	model := graph.NewModel()
	index := map[string]graph.ResourceID{} // "type.name" -> ID
	var diags []Diagnostic
	var resources []parsedResource

	// Parse every file once up front so the module pre-pass and the resource
	// pass share the same trees.
	parsed := make(map[string]*hclsyntax.Body, len(names))
	for _, name := range names {
		f, pd := hclsyntax.ParseConfig([]byte(files[name]), name, hcl.Pos{Line: 1, Column: 1})
		if pd.HasErrors() {
			return nil, nil, fmt.Errorf("hcl: %s does not parse: %s", name, pd.Error())
		}
		body, ok := f.Body.(*hclsyntax.Body)
		if !ok {
			return nil, nil, fmt.Errorf("hcl: %s has an unexpected body type", name)
		}
		parsed[name] = body
	}

	// Module pre-pass: collect every module invocation and resolve the local
	// ones. dirToModule maps each cleaned local source dir to its graph.Module
	// index; several invocations of the same dir share one container — the
	// canvas shows the module source codebase once, not one box per
	// instantiation (the instantiations themselves are not yet modeled).
	dirToModule := map[string]int{}
	fileSet := make(map[string]bool, len(names))
	for _, name := range names {
		fileSet[path.Clean(name)] = true
	}
	type moduleMeta struct {
		index int
		name  string
		file  string
		block *hclsyntax.Block
		local bool
	}
	var moduleMetas []moduleMeta
	for _, name := range names {
		for _, b := range parsed[name].Blocks {
			if b.Type != "module" {
				continue
			}
			meta := moduleMeta{index: -1, name: label(b), file: name, block: b}
			if len(b.Labels) == 1 {
				if src, ok := moduleSource(b); ok && isLocalSource(src) {
					if dir, ok := resolveLocalDir(src, name, fileSet); ok {
						meta.local = true
						if idx, claimed := dirToModule[dir]; claimed {
							meta.index = idx
						} else {
							meta.index = len(model.Modules)
							dirToModule[dir] = meta.index
							model.Modules = append(model.Modules, graph.Module{
								ID:        graph.NewResourceID(),
								Name:      b.Labels[0],
								Source:    src,
								Local:     true,
								Arguments: map[string]graph.AttrValue{},
								Resources: []graph.ResourceID{},
							})
						}
					}
				}
			}
			// meta.local stays false for remote/unknown/malformed sources, so
			// the module is honestly diagnosed below.
			moduleMetas = append(moduleMetas, meta)
		}
	}

	// Pass 1: register every resource so references can resolve across files.
	for _, name := range names {
		body := parsed[name]
		ownDir, inModule := owningModuleDir(dirToModule, name)
		for _, b := range body.Blocks {
			switch {
			case b.Type == "resource":
				if len(b.Labels) != 2 {
					diags = append(diags, Diagnostic{File: name, Reason: "resource block needs exactly a type and a name label"})
					continue
				}
				typ, nm := b.Labels[0], b.Labels[1]
				addr := typ + "." + nm
				if _, dup := index[addr]; dup {
					diags = append(diags, Diagnostic{File: name, Address: addr, Reason: "duplicate resource address; keeping the first"})
					continue
				}
				id := graph.NewResourceID()
				if err := model.AddResource(graph.Resource{ID: id, Type: typ, Name: nm}); err != nil {
					diags = append(diags, Diagnostic{File: name, Address: addr, Reason: err.Error()})
					continue
				}
				index[addr] = id
				resources = append(resources, parsedResource{id: id, block: b, file: name})
				if inModule {
					mod := &model.Modules[dirToModule[ownDir]]
					mod.Resources = append(mod.Resources, id)
				}
			case b.Type == "module":
				// Diagnosed (or resolved) in the module pass below.
			case (b.Type == "variable" || b.Type == "output") && inModule:
				// A resolved module's interface — the module grouping covers it.
			case !structuralBlocks[b.Type]:
				diags = append(diags, Diagnostic{File: name, Reason: fmt.Sprintf("%q block not imported yet", b.Type)})
			}
		}
	}

	// Module pass: unresolved (remote or unknown source) invocations diagnose;
	// resolved ones get their arguments converted against the resource index.
	// Representable arguments (literals, references to imported resources) are
	// stored on the Module; the rest are reported as ONE aggregated diagnostic
	// per invocation — the module's arguments are not rendered yet, so a
	// per-argument stream would bury the report (real repos pass dozens of
	// var/map values into every module).
	for _, mr := range moduleMetas {
		if mr.index < 0 {
			diags = append(diags, Diagnostic{File: mr.file, Reason: `"module" block not imported yet`})
			continue
		}
		mod := &model.Modules[mr.index]
		src := []byte(files[mr.file])
		skipped := 0
		for _, an := range sortedKeys(mr.block.Body.Attributes) {
			if an == "source" || an == "version" {
				continue
			}
			val, d := convertExpr(mr.block.Body.Attributes[an].Expr, src, index)
			if d != nil {
				skipped++
				continue
			}
			mod.Arguments[an] = val
		}
		if skipped > 0 {
			diags = append(diags, Diagnostic{
				File:    mr.file,
				Address: "module." + mr.name,
				Reason:  "module arguments not representable",
			})
		}
	}

	// Pass 2: resolve each resource's attributes against the address index.
	for _, pr := range resources {
		addr := addressOf(model, pr.id)
		src := []byte(files[pr.file])

		// Nested blocks (ingress {}, vpc_config {}, ebs_block_device {}, …):
		// convert each recursively into a graph.Block, keeping source order and
		// reporting — never guessing — anything its contents cannot represent.
		blocks, blockDiags := convertBlocks(src, pr.block.Body.Blocks, index)
		for i := range blockDiags {
			d := &blockDiags[i]
			d.File, d.Address = pr.file, addr
		}
		diags = append(diags, blockDiags...)
		if len(blocks) > 0 {
			if err := model.SetBlocks(pr.id, blocks); err != nil {
				diags = append(diags, Diagnostic{File: pr.file, Address: addr, Reason: err.Error()})
			}
		}

		attrNames := make([]string, 0, len(pr.block.Body.Attributes))
		for n := range pr.block.Body.Attributes {
			attrNames = append(attrNames, n)
		}
		sort.Strings(attrNames) // deterministic
		for _, an := range attrNames {
			val, d := convertExpr(pr.block.Body.Attributes[an].Expr, src, index)
			if d != nil {
				d.File, d.Address, d.Attribute = pr.file, addr, an
				diags = append(diags, *d)
				continue
			}
			if err := model.SetAttribute(pr.id, an, val); err != nil {
				diags = append(diags, Diagnostic{File: pr.file, Address: addr, Attribute: an, Reason: err.Error()})
			}
		}
	}

	// Edges mirror the refs so the canvas can draw connections without
	// re-deriving them; the generator ignores them and uses the refs directly.
	model.Edges = model.DeriveEdges()
	return model, diags, nil
}

// label returns a block's first label, or "" when it has none.
func label(b *hclsyntax.Block) string {
	if len(b.Labels) == 0 {
		return ""
	}
	return b.Labels[0]
}

// moduleSource reads a module block's source argument as a literal string,
// reporting false when it is absent or not a plain string literal.
func moduleSource(b *hclsyntax.Block) (string, bool) {
	a, ok := b.Body.Attributes["source"]
	if !ok {
		return "", false
	}
	val, err := a.Expr.Value(nil)
	if err != nil || val.IsNull() || !val.Type().Equals(cty.String) {
		return "", false
	}
	return val.AsString(), true
}

// isLocalSource reports whether a module source is an unambiguous local
// filesystem path. Terraform treats a bare "a/b/c" as a registry shorthand and
// "git::…" / scheme'd URLs as remote, so only ./ and ../ prefixes (and other
// paths with fewer than three segments) count as local.
func isLocalSource(src string) bool {
	if strings.HasPrefix(src, "./") || strings.HasPrefix(src, "../") {
		return true
	}
	if strings.Contains(src, "://") || strings.HasPrefix(src, "git::") || strings.Contains(src, "//") {
		return false
	}
	segs := strings.Split(strings.Trim(src, "/"), "/")
	return len(segs) < 3
}

// resolveLocalDir resolves a local module source relative to the file that
// declares it, against the imported file-key space, and reports whether any
// imported file lives under that directory. File keys share one namespace (the
// browser keys folder picks by webkitRelativePath), so joining the source onto
// the declaring file's own directory resolves to the same space.
func resolveLocalDir(src, blockFile string, fileSet map[string]bool) (string, bool) {
	dir := path.Clean(path.Join(path.Dir(blockFile), src))
	if fileSet[dir] {
		return dir, true
	}
	for k := range fileSet {
		if strings.HasPrefix(k, dir+"/") {
			return dir, true
		}
	}
	return "", false
}

// owningModuleDir returns the deepest local module directory that contains
// fileKey (its own source dir), so a resource inside a nested module belongs to
// the nested module, not its parent.
func owningModuleDir(dirToModule map[string]int, fileKey string) (string, bool) {
	best, bestLen := "", -1
	for d := range dirToModule {
		if fileKey == d || strings.HasPrefix(fileKey, d+"/") {
			if len(d) > bestLen {
				best, bestLen = d, len(d)
			}
		}
	}
	return best, bestLen >= 0
}

func addressOf(m *graph.Model, id graph.ResourceID) string {
	if r, ok := m.FindResource(id); ok {
		return r.Address()
	}
	return ""
}

// convertBlocks converts a list of nested HCL blocks into graph.Blocks,
// preserving source order. Each block is converted recursively; any construct
// inside a block that cannot be represented is reported as a Diagnostic and
// skipped, never guessed. Diagnostics carry only Reason and a block-path
// Attribute; the caller fills in File/Address.
func convertBlocks(src []byte, blocks hclsyntax.Blocks, index map[string]graph.ResourceID) ([]graph.Block, []Diagnostic) {
	var out []graph.Block
	var diags []Diagnostic
	for _, nb := range blocks {
		b, d := convertBlock(src, nb, index)
		if b != nil {
			out = append(out, *b)
		}
		diags = append(diags, d...)
	}
	return out, diags
}

// convertBlock converts one nested block, returning (nil, diags) when the
// block must be skipped entirely. Blocks with labels (the dynamic and
// provisioner/connection forms) are skipped: a graph.Block has no label field,
// so preserving them would require guessing the label's role. Each attribute
// and sub-block recurses through the same conversion the resource body uses,
// so references resolve against the same address index.
func convertBlock(src []byte, blk *hclsyntax.Block, index map[string]graph.ResourceID) (*graph.Block, []Diagnostic) {
	if len(blk.Labels) > 0 {
		return nil, []Diagnostic{{
			Attribute: blk.Type,
			Reason:    fmt.Sprintf("%q block with labels not supported yet", blk.Type),
		}}
	}

	var diags []Diagnostic
	out := graph.Block{Type: blk.Type, Attributes: map[string]graph.AttrValue{}}
	for _, an := range sortedKeys(blk.Body.Attributes) {
		val, d := convertExpr(blk.Body.Attributes[an].Expr, src, index)
		if d != nil {
			d.Attribute = blockAttrPath(blk.Type, an)
			diags = append(diags, *d)
			continue
		}
		out.Attributes[an] = val
	}
	sub, subDiags := convertBlocks(src, blk.Body.Blocks, index)
	if len(subDiags) > 0 {
		for i := range subDiags {
			// Prepend the parent block to the nested block's path.
			d := &subDiags[i]
			if d.Attribute == "" {
				d.Attribute = blk.Type
			} else {
				d.Attribute = blk.Type + "." + d.Attribute
			}
		}
		diags = append(diags, subDiags...)
	}
	if len(sub) > 0 {
		out.Blocks = sub
	}
	return &out, diags
}

// blockAttrPath names one argument inside a nested block's lineage.
func blockAttrPath(typ, name string) string {
	return typ + "." + name
}

// sortedKeys returns the attribute map's keys in lexical order so block
// conversion is deterministic regardless of map iteration order.
func sortedKeys[V any](m map[string]V) []string {
	names := make([]string, 0, len(m))
	for n := range m {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// convertExpr turns one HCL expression into an AttrValue, or returns a
// Diagnostic (with only Reason set; the caller fills in file/address/attr) when
// the expression is not a literal, a resource reference, or a list of those.
func convertExpr(expr hclsyntax.Expression, src []byte, index map[string]graph.ResourceID) (graph.AttrValue, *Diagnostic) {
	switch e := expr.(type) {
	case *hclsyntax.ScopeTraversalExpr:
		return convertTraversal(e.Traversal, index)
	case *hclsyntax.TemplateWrapExpr:
		// A template that is exactly one interpolation, e.g.
		// "${aws_vpc.main.id}" — the Terraform 0.11-era reference style. Unwrap
		// and convert the inner expression (usually a traversal).
		return convertExpr(e.Wrapped, src, index)
	case *hclsyntax.TemplateExpr:
		// A quoted string. A single-part template is either a plain literal
		// ("t2.micro") or a lone interpolation ("${aws_vpc.main.id}"); convert
		// the sole part so the old quoted-reference style still resolves. A
		// multi-part template concatenates literal text and interpolations
		// (e.g. "prefix-${x}"), which the flat model cannot represent.
		if len(e.Parts) == 1 {
			return convertExpr(e.Parts[0], src, index)
		}
		return graph.AttrValue{}, &Diagnostic{Reason: "interpolated string with multiple parts is not representable"}
	case *hclsyntax.TupleConsExpr:
		items := make([]graph.AttrValue, 0, len(e.Exprs))
		for _, sub := range e.Exprs {
			v, d := convertExpr(sub, src, index)
			if d != nil {
				return graph.AttrValue{}, &Diagnostic{Reason: "list element not representable: " + d.Reason}
			}
			items = append(items, v)
		}
		return graph.List(items...), nil
	default:
		// Everything else must be a constant to be representable: evaluating
		// with a nil context succeeds for pure literals and fails for anything
		// referencing a symbol (interpolations, functions, var/local/…).
		val, vd := expr.Value(nil)
		if vd.HasErrors() {
			return graph.AttrValue{}, &Diagnostic{Reason: "not a literal or resource reference (interpolation, function, or variable)"}
		}
		return convertScalar(val, expr, src)
	}
}

// convertTraversal resolves a resource-attribute traversal (type.name.attr)
// against the address index. Non-resource roots and unknown addresses are
// diagnosed and skipped rather than emitted as dangling references.
func convertTraversal(trav hcl.Traversal, index map[string]graph.ResourceID) (graph.AttrValue, *Diagnostic) {
	if len(trav) < 3 {
		return graph.AttrValue{}, &Diagnostic{Reason: "reference is not a resource attribute (type.name.attribute)"}
	}
	root, ok0 := trav[0].(hcl.TraverseRoot)
	a1, ok1 := trav[1].(hcl.TraverseAttr)
	a2, ok2 := trav[2].(hcl.TraverseAttr)
	if !ok0 || !ok1 || !ok2 {
		return graph.AttrValue{}, &Diagnostic{Reason: "reference has an index or unexpected shape"}
	}
	if nonResourceRoots[root.Name] {
		return graph.AttrValue{}, &Diagnostic{Reason: fmt.Sprintf("reference to %s.* is not a resource (not modeled yet)", root.Name)}
	}
	addr := root.Name + "." + a1.Name
	id, ok := index[addr]
	if !ok {
		return graph.AttrValue{}, &Diagnostic{Reason: fmt.Sprintf("reference to %s not found among the imported resources", addr)}
	}
	return graph.Ref(id, a2.Name), nil
}

// convertScalar turns a constant cty value into a literal AttrValue. Numbers
// keep their exact source text (via the expression's range) so precision and
// int-vs-float identity survive, mirroring how the generator stores them.
func convertScalar(val cty.Value, expr hclsyntax.Expression, src []byte) (graph.AttrValue, *Diagnostic) {
	if val.IsNull() {
		return graph.AttrValue{}, &Diagnostic{Reason: "null values are not modeled"}
	}
	switch val.Type() {
	case cty.String:
		return graph.String(val.AsString()), nil
	case cty.Bool:
		return graph.Bool(val.True()), nil
	case cty.Number:
		rng := expr.Range()
		if rng.Start.Byte >= 0 && rng.End.Byte <= len(src) && rng.Start.Byte < rng.End.Byte {
			if v := graph.NumberText(string(src[rng.Start.Byte:rng.End.Byte])); v.Valid() {
				return v, nil
			}
		}
		// Fall back to cty's canonical form if the source text isn't a clean
		// literal (e.g. a parenthesised or negated expression).
		return graph.NumberText(val.AsBigFloat().Text('f', -1)), nil
	default:
		return graph.AttrValue{}, &Diagnostic{Reason: "unsupported value type " + val.Type().FriendlyName()}
	}
}
