/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Terraform from a graph model
         * @description Validates the supplied graph model and renders it to Terraform files. A 422 is returned if the model is not generator-safe (dangling references, a dependency cycle, invalid identifiers, and so on). The output is syntactically valid HCL; it is not checked against provider schemas.
         */
        post: operations["generate-hcl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Greet a user by name
         * @description Trivial endpoint that exercises the hexagonal layering end-to-end (HTTP adapter → application use case → domain function).
         */
        get: operations["hello-greet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Terraform into a graph model
         * @description Parses Terraform source statically (no terraform binary) into a graph model. It reads resource blocks, scalar literals, references between resources, and lists of those. Anything it cannot yet represent — nested blocks, references to var/data/module, functions, count/for_each — is returned as a diagnostic and skipped, never guessed. A 422 is returned only when the HCL does not parse.
         */
        post: operations["import-terraform"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 OK if the process is running. Does not check downstream dependencies.
         */
        get: operations["health-liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttrValue: {
            /** @description Referenced attribute name (when kind=ref), emitted bare in HCL. */
            attribute?: string;
            /** @description Child values (when kind=list). */
            items?: components["schemas"]["AttrValue"][] | null;
            /**
             * @description Value variant: literal scalar, reference to another resource, or list.
             * @enum {string}
             */
            kind: "literal" | "ref" | "list";
            /**
             * @description Scalar type (when kind=literal).
             * @enum {string}
             */
            litType?: "string" | "number" | "bool";
            /** @description Referenced resource ID (when kind=ref). */
            target?: string;
            /** @description Canonical literal text (when kind=literal); numbers are kept as text to preserve precision. */
            value?: string;
        };
        Block: {
            attributes?: {
                [key: string]: components["schemas"]["AttrValue"];
            };
            blocks?: components["schemas"]["Block"][] | null;
            /**
             * @description Block type label, e.g. ingress, egress, default_action.
             * @example ingress
             */
            type: string;
        };
        Diagnostic: {
            address?: string;
            attribute?: string;
            file?: string;
            reason: string;
        };
        Edge: {
            attribute: string;
            from: string;
            to: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GenerateOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/GenerateOutputBody.json
             */
            readonly $schema?: string;
            /** @description Generated Terraform files, keyed by filename (e.g. main.tf). */
            files: {
                [key: string]: string;
            };
        };
        GreetOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/GreetOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description The generated greeting.
             * @example Hello, calco
             */
            message: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Service status.
             * @example ok
             */
            status: string;
        };
        ImportInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ImportInputBody.json
             */
            readonly $schema?: string;
            /** @description Terraform sources keyed by filename (e.g. main.tf). */
            files: {
                [key: string]: string;
            };
        };
        ImportOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ImportOutputBody.json
             */
            readonly $schema?: string;
            /** @description Constructs that could not be represented and were skipped (empty when everything imported cleanly). */
            diagnostics: components["schemas"]["Diagnostic"][] | null;
            /** @description The imported graph model. Positions are unset; the client lays it out. */
            model: components["schemas"]["Model"];
        };
        Model: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Model.json
             */
            readonly $schema?: string;
            edges?: components["schemas"]["Edge"][] | null;
            outputs?: components["schemas"]["Output"][] | null;
            resources?: components["schemas"]["Resource"][] | null;
            variables?: components["schemas"]["Variable"][] | null;
        };
        Output: {
            description?: string;
            name: string;
            sensitive?: boolean;
            value: components["schemas"]["AttrValue"];
        };
        Position: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        Resource: {
            attributes?: {
                [key: string]: components["schemas"]["AttrValue"];
            };
            /** @description Nested blocks, in order (e.g. ingress rules on a security group). */
            blocks?: components["schemas"]["Block"][] | null;
            /** @description Stable internal resource ID (UUID). */
            id: string;
            /**
             * @description Terraform name slug.
             * @example main
             */
            name: string;
            position?: components["schemas"]["Position"];
            /**
             * @description Terraform resource type.
             * @example aws_vpc
             */
            type: string;
        };
        Variable: {
            default?: components["schemas"]["AttrValue"];
            description?: string;
            name: string;
            sensitive?: boolean;
            /** @example string */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "generate-hcl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Model"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "hello-greet": {
        parameters: {
            query?: {
                /** @description Name to greet. Defaults to 'world' if empty. */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreetOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "import-terraform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
